<a href="https://colab.research.google.com/github/manowar077/Machine-Learning/blob/main/Numpy_For_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import time

***claculation using List***

In [ ]:
a=[1,2,3,4,5,6,7,8,9,10]*1000000

start=time.time()
for i in range(len(a)):
  a[i]=a[i]*2
end=time.time()
print("\nTime Taken For List :",end-start)


Time Taken For List : 1.362264633178711


**And Through Numpay**

In [ ]:
a=[1,2,3,4,5,6,7,8,9,10]*1000000
b=np.array(a)
start=time.time()
new_b=b*2
end=time.time()
print("\Time Taken for Numpay array :",end-start)

\Time Taken for Numpay array : 0.03906679153442383


<>:6: SyntaxWarning: invalid escape sequence '\T'
<>:6: SyntaxWarning: invalid escape sequence '\T'
/tmp/ipykernel_3071/3851265883.py:6: SyntaxWarning: invalid escape sequence '\T'
  print("\Time Taken for Numpay array :",end-start)


In [ ]:
##memory efficient

In [ ]:
import sys

In [ ]:
a=[1,2,3,4,5]
arr=np.array(a)
print("List Size :",sys.getsizeof(a))
print("Array Size :",arr.nbytes)

List Size : 104
Array Size : 40


**Dimension And Shapes**

In [ ]:
a=np.array([[[[[]]]]])
print(a.ndim)
print(a.shape)


5
(1, 1, 1, 1, 0)


In [ ]:
range=np.arange(1,10,2) #(start,end,step)

In [ ]:
range

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

evenly space Array between two array

In [ ]:
arr=np.linspace(1,1,5)
arr

array([1., 1., 1., 1., 1.])

Logrithemic space array

In [ ]:
arr=np.logspace(10,20,10) #logrethemic scale array -> 10^10 ->10
arr #(starting power,ending power,numofvalue)

array([1.00000000e+10, 1.29154967e+11, 1.66810054e+12, 2.15443469e+13,
       2.78255940e+14, 3.59381366e+15, 4.64158883e+16, 5.99484250e+17,
       7.74263683e+18, 1.00000000e+20])

np.zeros

In [ ]:
#array full of zero(creating matrices full on zeros )
arr=np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr=np.zeros([2,4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Np.ones

In [ ]:
arr=np.ones([4,2]) #creating a matrices full of ones
arr


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

**create an array full of any value **

In [ ]:
arr=np.full(10,2)
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
arr=np.full([2,3],5)
arr

array([[5, 5, 5],
       [5, 5, 5]])

np.empty

In [ ]:
arr=np.empty #uninitilized array ->create an array without setting any value
arr

<function numpy.empty>

np.random

In [ ]:
arr=np.random.rand(10) #random floats(0 t0 1)
arr


array([0.34177426, 0.9215819 , 0.6905655 , 0.88846974, 0.59418371,
       0.15501321, 0.43885866, 0.25698633, 0.2892451 , 0.38825128])

In [ ]:
arr=np.random.rand(2,3)
arr

array([[0.98019392, 0.69018637, 0.80972791],
       [0.17347802, 0.03130262, 0.26138626]])

np.random.randn()

In [ ]:
import numpy as np
arr=np.random.randn(2,3) # random floats from normal standard normal distibution
arr

array([[ 0.49941088,  0.76876348, -1.00290947],
       [-0.17207262, -0.88951869,  1.67418844]])

np.random.randint()

In [ ]:
arr=np.random.randint(10,99) # generating any random number between range (start ,stop,numberof value)
arr

84

In [ ]:
arr=np.random.randint(10,99,7) # generating any random number between range (start ,stop,numberof value)
arr

array([38, 74, 79, 75, 19, 43, 75])

In [ ]:
arr=np.random.randint(10,99,size=(2,3)) # generating any random number between range (start ,Dimension of matrices)
arr

array([[78, 88, 13],
       [16, 70, 87]])

*Numpy Data Types And Type Casting*

In [ ]:
arr=np.array([1,2,3,4,5.1])
arr

array([1. , 2. , 3. , 4. , 5.1])

In [ ]:
arr=np.array([1,2,4,5,6.7])
arr
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
arr=np.array([1,2,56,4.5],dtype=np.float64)

***type-casting***

In [ ]:
arr=np.array([1,2,3])
arr.dtype

dtype('int64')

In [ ]:
new_arr=arr.astype(np.float64)
new_arr
new_arr.dtype

dtype('float64')

In [ ]:
#type casting error
arr=np.array("1","2","hello")
arr2=arr.astype(np.int64)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

**Array Re-Shaping**

In [ ]:
#reshape
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
reshape2=reshaped.reshape(3,2)
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
#Ravel -> convert 1D Array
ravel=reshape2.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [ ]:
ravel[0]=100
print(ravel)
print(reshape2)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [ ]:
#flatten -> to 1D Array
#-> return a copy of the array
flat=reshape2.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [ ]:
flat[0]=1
reshape2

array([[100,   2],
       [  3,   4],
       [  5,   6]])

**Arthematic Operation**

In [ ]:
#np.take -> built in function to perform indexing and slicing
arr=np.array([10,20,30,40,50])
ind=[0,2]
print(np.take(arr,ind))

[10 30]


*Iterating with nd.iter

In [ ]:
arr=np.array([[1,2],[3,4]])
for x in np.nditer(arr):
  print(x,end=" ")

1 2 3 4 

ndenumerate() -> both index + value


In [ ]:
arr=np.array([[1,2],[3,4]])
for x in np.ndenumerate(arr):
  print(arr,x)

[[1 2]
 [3 4]] ((0, 0), np.int64(1))
[[1 2]
 [3 4]] ((0, 1), np.int64(2))
[[1 2]
 [3 4]] ((1, 0), np.int64(3))
[[1 2]
 [3 4]] ((1, 1), np.int64(4))


**Views vs Copies**

In [ ]:
arr=np.array([1,2,3,4,5,6])
view=arr[1:3]
view

array([2, 3])

In [ ]:
view[0]=200

In [ ]:
arr

array([  1, 200,   3,   4,   5,   6])

In [ ]:
#copy
copy=arr[1:3].copy()
copy

array([200,   3])

In [ ]:
copy[0]=2
copy

array([2, 3])

In [ ]:
arr

array([  1, 200,   3,   4,   5,   6])

**Transpose**

In [ ]:
arr=np.array([[1,2],[3,4]])
print(arr.transpose())

[[1 3]
 [2 4]]


In [ ]:
#swapaxes -> swap 2 specific axes in a matrix.
arr=np.array([[[1,2],[3,4]]])
arr.shape

(1, 2, 2)

In [ ]:
swap=np.swapaxes(arr,0,1)
swap.shape

(2, 1, 2)

**Concatenation**

In [ ]:
a=np.array([1,2])
b=np.array([3,4])
combine=np.concatenate((a,b))
combine

array([1, 2, 3, 4])

In [ ]:
#vertical stack
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
vertical=np.vstack((arr1,arr2))
vertical

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
#horizontal-stack
print(np.hstack((arr1,arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [ ]:
arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(np.stack((arr1,arr2),axis=0)) #where 0->rowwise 1->columnwise

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#splitting the array
arr=np.array([1,2,3,4,5,6])
split=np.split(arr,3)
split

[array([1, 2]), array([3, 4]), array([5, 6])]

In [ ]:
#horizontal split and vertical split
arr=np.array([[1,2],[3,4]])
print(np.hsplit(arr,2))
print(np.vsplit(arr,2))

[array([[1],
       [3]]), array([[2],
       [4]])]
[array([[1, 2]]), array([[3, 4]])]


In [ ]:
#repeating
arr=np.array([1,2,3])
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3]


In [ ]:
print(np.tile(arr,3))

[1 2 3 1 2 3 1 2 3]


Aggregate function

In [ ]:
arr=np.array([1,2,3])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))

6
1
3
2.0
2.0


In [ ]:
np.std(arr)

np.float64(0.816496580927726)

In [ ]:
np.var(arr)

np.float64(0.6666666666666666)

Rowwise operation

In [ ]:
import numpy as np
arr=np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [ ]:
print(np.sum(arr,axis=0)) #columnwise
print(np.sum(arr,axis=1)) #rowwise

[4 6]
[3 7]


Cumulative Sum of an Array

In [ ]:
print(np.cumsum(arr)) #return firstele then addition with next ele

[ 1  3  6 10]


In [ ]:
print(np.cumprod(arr))

[ 1  2  6 24]


**Conditional based choices in numpy**

In [ ]:
arr
result=np.where(arr<2,"low","high")
result

array([['low', 'high'],
       ['high', 'high']], dtype='<U4')

In [ ]:
print(np.argwhere(arr<4))

[[0 0]
 [0 1]
 [1 0]]


In [ ]:
#masking
mask=np.logical_and(arr>1,arr<3)
mask

array([[False,  True],
       [False, False]])

In [ ]:
mask=np.logical_and(arr>3,arr<5)
mask

array([[False, False],
       [False,  True]])

In [ ]:
arr[mask]

array([4])

In [ ]:
#logical-or
mask=np.logical_or(arr>1,arr<3)
mask

array([[ True,  True],
       [ True,  True]])

In [ ]:
arr[mask]

array([1, 2, 3, 4])

**Broadcasting**

**Broadcasting** in NumPy is the mechanism that lets NumPy perform arithmetic operations on arrays of **different shapes** without explicitly copying data — it automatically "stretches" the smaller array across the larger one so their shapes become compatible.

**The problem it solves**

Without broadcasting, operations like `array + scalar` or adding arrays of different shapes would require you to manually reshape/tile the smaller array to match. Broadcasting removes that boilerplate.

```python
import numpy as np

a = np.array([1, 2, 3])
b = 5
print(a + b)  # [6 7 8]
```

Here, `5` is conceptually "broadcast" to `[5, 5, 5]` and added elementwise — but NumPy doesn't actually create that array in memory; it's done efficiently under the hood.

**The broadcasting rules**

When operating on two arrays, NumPy compares their shapes **element-wise, starting from the trailing (rightmost) dimension**. Two dimensions are compatible when:
1. They are **equal**, OR
2. One of them is **1** (or missing entirely)

If neither condition holds for any dimension, you get a `ValueError: operands could not be broadcast together`.

**Example — vector + matrix**

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])      # shape (2, 3)

b = np.array([10, 20, 30])     # shape (3,)

print(A + b)
# [[11 22 33]
#  [14 25 36]]
```

Here, `b` (shape `(3,)`) is broadcast across each row of `A` (shape `(2,3)`), because trailing dimensions match (`3 == 3`), and the missing leading dimension in `b` is treated as `1`, which stretches to match `2`.

**Example — column vector + row vector**

```python
col = np.array([[1], [2], [3]])   # shape (3, 1)
row = np.array([10, 20, 30])      # shape (3,)

print(col + row)
# [[11 21 31]
#  [12 22 32]
#  [13 23 33]]
```

This produces a `(3,3)` result — both arrays get stretched along their size-1 dimension to form an outer-product-like grid. This pattern is genuinely useful (e.g., building distance matrices, outer sums).

**Visualizing the shape-matching**

| Array | Shape |
|---|---|
| A | `(2, 3)` |
| B | `(3,)` → treated as `(1, 3)` |
| Result | `(2, 3)` |

```
A:      2 x 3
B:          3   (implicitly 1 x 3)
------------
Result: 2 x 3
```

**Why it matters practically**
- **Performance:** avoids creating unnecessary copies of data — broadcasting is implemented in C and doesn't allocate the "stretched" array in memory.
- **Cleaner code:** you write `A + b` instead of manually tiling `b` with `np.tile()`.
- Extremely common in data science / ML code: normalizing data (`(X - mean) / std`), adding bias vectors in neural nets, computing pairwise distances, etc.

**Common failure case**

```python
a = np.zeros((3, 4))
b = np.zeros((3,))
a + b  # ValueError!
```

This fails because trailing dimensions are `4` vs `3` — neither equal nor `1`. You'd need `b` reshaped to `(3, 1)` (via `b.reshape(3,1)` or `b[:, None]`) if you wanted it to broadcast against the rows instead of columns.

Want me to show a practical example — like normalizing a dataset or computing a pairwise distance matrix — where broadcasting actually saves real code and runtime?

In [4]:
#without Broadcasting
prices=[100,200,300]
discount=10
start=time.time()
final_prices=[]
for price in prices:
  final_prices.append(price-(price*discount/100))
final_prices
end=time.time()
print("\nTime Taken Without Broadcasting :",end-start)


Time Taken Without Broadcasting : 0.00013899803161621094


In [6]:
import numpy as np
import time

# Python list
prices = list(range(10_000_000))

start = time.time()

final_prices = []

for price in prices:
    final_prices.append(price - (price * 10 / 100))

end = time.time()

print("Without NumPy:", end - start)

Without NumPy: 2.403815269470215


In [5]:
#broadcasting->
import numpy as np
prices=np.array([100,200,300])
discount=10
start=time.time()
final_prices=prices-(prices*discount/100)
final_prices
end=time.time()
print("\nTime Taken With Broadcasting :",end-start)


Time Taken With Broadcasting : 0.00016498565673828125


In [7]:
import numpy as np
import time

prices = np.arange(10_000_000)

start = time.time()

final_prices = prices - (prices * 10 / 100)

end = time.time()

print("With NumPy:", end - start)

With NumPy: 0.22811079025268555


**Vectorization**

# Vectorization in NumPy

**Vectorization** means performing operations on an entire array at once instead of using Python loops.

## Without Vectorization ❌

```python
prices = [100, 200, 300]
discount = 10

final_prices = []

for price in prices:
    final_prices.append(price - (price * discount / 100))

print(final_prices)
```

Here, Python processes each element individually:

```text
100 → calculate
200 → calculate
300 → calculate
```

Output:

```text
[90.0, 180.0, 270.0]
```

---

## With Vectorization ✅

```python
import numpy as np

prices = np.array([100, 200, 300])
discount = 10

final_prices = prices - (prices * discount / 100)

print(final_prices)
```

Output:

```text
[ 90. 180. 270.]
```

Here, you write one operation for the entire array.

```text
[100, 200, 300]
        ↓
   One operation
        ↓
[90, 180, 270]
```

## Vectorization vs Broadcasting

These two concepts are related but different:

### Vectorization

Performing an operation on an entire array without explicitly writing a Python loop.

```python
prices * 2
```

### Broadcasting

Allows NumPy arrays with different shapes—or a scalar and an array—to work together.

```python
prices * discount
```

Here, `discount` is conceptually applied to every element.

### Simple Difference 💡

```text
Vectorization → Avoid Python loops

Broadcasting → Makes different-sized arrays compatible
               for operations
```

For your previous example:

```python
final_prices = prices - (prices * discount / 100)
```

**Vectorization** allows the calculation to run on the entire array, while **broadcasting** allows the scalar `discount` to operate with every element of `prices`.


In [9]:
arr1=np.array([1,2,3,45,56,76])
arr2=np.array([9,8,7,6,5,32])
result=arr1+arr2
result

array([ 10,  10,  10,  51,  61, 108])

# **Handaling Missing Value iN Numpy**

# Handling Missing Values in NumPy

In NumPy, missing values are commonly represented using:

```python
np.nan
```

`NaN` means **Not a Number**.

First, import NumPy:

```python
import numpy as np
```

---

## 1. Creating an Array with Missing Values

```python
arr = np.array([10, 20, np.nan, 40, 50])

print(arr)
```

Output:

```text
[10. 20. nan 40. 50.]
```

---

## 2. Finding Missing Values

Use `np.isnan()`:

```python
arr = np.array([10, 20, np.nan, 40, np.nan])

print(np.isnan(arr))
```

Output:

```text
[False False  True False  True]
```

`True` means that the value is missing.

### Count Missing Values

```python
np.isnan(arr).sum()
```

Output:

```text
2
```

---

## 3. Remove Missing Values

You can remove `NaN` values using:

```python
clean_arr = arr[~np.isnan(arr)]

print(clean_arr)
```

Output:

```text
[10. 20. 40.]
```

### How does this work?

```python
np.isnan(arr)
```

gives:

```text
[False False True False True]
```

The `~` operator reverses the values:

```text
[True True False True False]
```

Then NumPy selects only the `True` positions.

---

## 4. Replace Missing Values

### Replace with Zero

```python
arr = np.array([10, 20, np.nan, 40])

arr[np.isnan(arr)] = 0

print(arr)
```

Output:

```text
[10. 20.  0. 40.]
```

---

## 5. Replace Missing Values with the Mean

```python
arr = np.array([10, 20, np.nan, 40, 50])

mean_value = np.nanmean(arr)

arr[np.isnan(arr)] = mean_value

print(arr)
```

Output:

```text
[10. 20. 30. 40. 50.]
```

### Why `np.nanmean()`?

Normal mean:

```python
np.mean(arr)
```

returns:

```text
nan
```

because the array contains a missing value.

But:

```python
np.nanmean(arr)
```

ignores `NaN` values.

```text
(10 + 20 + 40 + 50) / 4 = 30
```

---

# Other Useful Functions

NumPy provides several functions that automatically ignore `NaN` values:

| Function         | Purpose              |
| ---------------- | -------------------- |
| `np.nanmean()`   | Mean ignoring NaN    |
| `np.nansum()`    | Sum ignoring NaN     |
| `np.nanmax()`    | Maximum ignoring NaN |
| `np.nanmin()`    | Minimum ignoring NaN |
| `np.nanmedian()` | Median ignoring NaN  |

### Example

```python
arr = np.array([10, 20, np.nan, 40])

print(np.nansum(arr))
```

Output:

```text
70.0
```

## Summary

```text
Find missing values    → np.isnan()
Count missing values   → np.isnan(arr).sum()
Remove missing values  → arr[~np.isnan(arr)]
Replace missing values → arr[np.isnan(arr)] = value
Ignore NaN in mean     → np.nanmean(arr)
```

💡 **Note:** For more advanced missing-data handling, especially in datasets with text, dates, and columns, **Pandas** is generally more convenient than NumPy.


In [10]:
#handle infinity number
arr=np.array([1,2,3,np.inf])
arr
np.isinf(arr)


array([False, False, False,  True])